-- MySQL Script generated by MySQL Workbench
-- Fri Feb 14 23:09:20 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema todo_db
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS todo_db;
USE `todo_db` ;

-- -----------------------------------------------------
-- Table user
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todo_db`.`user`
(
    `id`           INT AUTO_INCREMENT NOT NULL COMMENT 'id',
    `name`         VARCHAR(255)       NOT NULL COMMENT 'ユーザ名',
    `password`     VARCHAR(255)       NOT NULL COMMENT 'パスワード',
    `auth_token`   VARCHAR(255)       NOT NULL COMMENT '認証トークン',
    `existence`    INT                NOT NULL COMMENT 'ユーザの存在の有無',
    PRIMARY KEY (`id`)
)
ENGINE = InnoDB
COMMENT = 'ユーザ';


-- -----------------------------------------------------
-- Table todo
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todo_db`.`todo`
(
    `id`             INT AUTO_INCREMENT NOT NULL COMMENT 'id',
    `todo_user_id`   INT                NOT NULL COMMENT 'todoリストを作成したユーザのid',
    `todo_article`   VARCHAR(255)       NOT NULL COMMENT '内容',
    `todo_limit`     DATETIME                    COMMENT 'TODOの期限',
    `todo_tag_id`    INT                NOT NULL COMMENT 'タグ',
    `todo_complete`  INT                NOT NULL COMMENT '終了したかどうか',
    `todo_existence` INT                NOT NULL COMMENT '削除したかどうか',
    PRIMARY KEY (`id`),
    FOREIGN KEY('todo_user_id')  REFERENCES user('id') ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY('todo_tag_id') REFERENCES tag('id')  ON UPDATE CASCADE ON DELETE CASCADE,
)
ENGINE = InnoDB
COMMENT = 'ToDo List';


-- -----------------------------------------------------
-- Table tag
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todo_db`.`tag`
(
    `id`   INT          NOT NULL COMMENT 'id',
    `tag_data` VARCHAR(255) NOT NULL COMMENT '内容',
    PRIMARY KEY (`id`)
)
ENGINE = InnoDB
COMMENT = 'タグ';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
